test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID: 	 	YOUR_CREDENTIAL_HERE
  PAYPAL_CLIENT_SECRET: 	YOUR_CREDENTIAL_HERE
  STRIPE_PUBLISHABLE_KEY:	pk_test_80dWzZcjPAM3r9b8F4BqjXpZ00EXnofFW3
  STRIPE_SECRET_KEY: 	sk_test_Nnrqyh6s7Qh0U9FbRNNei88v00QEgHgUvG

development:
  <<: *default