# Add configuration values here, as shown below.
#
pusher_app_id: "2954"
pusher_key: 7381a978f7dd7f9a1117
pusher_secret: abdc3b896a0ffb85d373
#
production:
stripe_api_key: sk_test_Nnrqyh6s7Qh0U9FbRNNei88v00QEgHgUvG
stripe_publishable_key: pk_test_80dWzZcjPAM3r9b8F4BqjXpZ00EXnofFW3
